(def MAXPLAYERS 4);
(def DEFAULTHEALTH 100);

([
  GAMETITLE: "Space Adventure",
  MAXPLAYERS: MAXPLAYERS,
  DEFAULTSTATS: ([
    HEALTH: DEFAULTHEALTH,
    AMMO: 50
  ]),
  UPGRADES: array(
    {+ DEFAULTHEALTH 20},
    {chr 85}
  )
]);
